language: node_js
sudo: 'false'
before_script: []
env:
  global:
    - secure: >-
        WrLb2X4TlnuYoKKGA/SOIU4Av4014D4BdSa3Ilr4KvkMO8w+nv6arCsrcPbIAW4PZ2dm98UHhTap9ryFUV/9z/j1v4eH4HA7g3/7OP2VKOn9lGwo1PqpPWYqVrBet/HiOdzoW3lKVX+LUteA4QnWA/Javbc79mBzxduN3vXxWq2Qrr5PKgvdASzxUFhliPwbcEJEtD1FamLQiDE8xCAcqElf8s0H2/LpYBmMR4xCE786Xooh+3LlVoOBbzTCVyCTgPW18fUAqn9S1rLoy3BVeaT7pV6XtiHPvdRUZAXD5ERHPAhVz4IOWtvgnSvEA6mJng4hzjFzwIAnbtAv0CichP89Kxh21ZLwu9FadVFHVE806IRolcFlAIiUoukImDsP7ePxYd7c0IuOy7r0PGwj6vh2N1mIDQjUu+YA0uHwDL1ZSXRXExSMtl7USMdt1KRWQ/WnWfHeuWWAcuuSnlBkkN5Mp1s0C9FPEUoFR/MluKHh+pfzmiGogNPa28Ii8EFopPYQBA5eMTXscnP+U5Y695fJTlwcTMREMFqtXiSnSIcxEie3BL/5dG+37+bdfFi2kzO10hpPPF2rLqf9iDFY7GQndE2lYXgK3bi14PsRpQbqC/6LtUASNtKYB056VUwnsZYNFma74G+9+53K0WwJxH25FDZM0WnWlH1EE90y6lI=
    - secure: >-
        aSeMS30cYEIBq0jCqJoyJgZBnOjhJjBF6gIXBoI/XOJRO1OGTmdish0w9Llikij1/8dwxPipjZAitxZ4nnQzmI0xegra58z3dTVt/DRyTMlkyWZpsuzUMBvww2FhleH6pALrM+k6MUqtLjABMKnzqDiQx7EceswFoDxb+UW1eTXpOXPixMDSGTaaFlund9wXb5avift5UyiBaSTm+Y2gN3xBVZxEgeQ7zYoqRLORfiusx/swoL/8HDDsZFI4Ria4jAcQ/JHG6dfs5EHulVR6YhwQzEnXQ0i+yAidKOVwEnUuABAMqrXpCfNeY/GNAXun1KmvqyZwBmWniVXyfiibR1asE1DepTGdSE0ZG249a9xSrzmJ0f1qiepwQCoNV4BAd2TrSck5qLSgNanRUDrfBoutld2bBM0sFT+XM34eYmatx93d4ScW/EZq3dsrCD9I62eQi8aAduz5iqA/NJ57eiy3xymUaDp2wXO6w9nwKZmJFfpJo3XTqb3VZGRz6+Yz+DWUw3l8+B1f6WiFjK5U6DKwfWWdTwTBswAkSOm0wsnERYzLqgJjS2QmjIbOpofczV21al0p+TkGlrU7VvmGVz1LShsgrhkj9fSvYRnjoUbCn3YBzdFdz0Zu426tajbkXKDFNKFTlK7Xp6jprYuEgqMFcRzXzwp/jlXhg9KyjDM=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
